// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.CouponDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CouponIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CouponIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CouponIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CouponIntegrationTest: @Transactional;
    
    @Autowired
    private CouponDataOnDemand CouponIntegrationTest.dod;
    
    @Test
    public void CouponIntegrationTest.testCountCoupons() {
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", dod.getRandomCoupon());
        long count = com.newland.beecode.domain.Coupon.countCoupons();
        org.junit.Assert.assertTrue("Counter for 'Coupon' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CouponIntegrationTest.testFindCoupon() {
        com.newland.beecode.domain.Coupon obj = dod.getRandomCoupon();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", obj);
        java.lang.Long id = obj.getCouponId();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Coupon.findCoupon(id);
        org.junit.Assert.assertNotNull("Find method for 'Coupon' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Coupon' returned the incorrect identifier", id, obj.getCouponId());
    }
    
    @Test
    public void CouponIntegrationTest.testFindAllCoupons() {
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", dod.getRandomCoupon());
        long count = com.newland.beecode.domain.Coupon.countCoupons();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Coupon', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.Coupon> result = com.newland.beecode.domain.Coupon.findAllCoupons();
        org.junit.Assert.assertNotNull("Find all method for 'Coupon' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Coupon' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CouponIntegrationTest.testFindCouponEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", dod.getRandomCoupon());
        long count = com.newland.beecode.domain.Coupon.countCoupons();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.Coupon> result = com.newland.beecode.domain.Coupon.findCouponEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Coupon' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Coupon' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CouponIntegrationTest.testFlush() {
        com.newland.beecode.domain.Coupon obj = dod.getRandomCoupon();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", obj);
        java.lang.Long id = obj.getCouponId();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Coupon.findCoupon(id);
        org.junit.Assert.assertNotNull("Find method for 'Coupon' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCoupon(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Coupon' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CouponIntegrationTest.testMerge() {
        com.newland.beecode.domain.Coupon obj = dod.getRandomCoupon();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", obj);
        java.lang.Long id = obj.getCouponId();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Coupon.findCoupon(id);
        boolean modified =  dod.modifyCoupon(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.Coupon merged = (com.newland.beecode.domain.Coupon) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getCouponId(), id);
        org.junit.Assert.assertTrue("Version for 'Coupon' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CouponIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", dod.getRandomCoupon());
        com.newland.beecode.domain.Coupon obj = dod.getNewTransientCoupon(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Coupon' identifier to be null", obj.getCouponId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Coupon' identifier to no longer be null", obj.getCouponId());
    }
    
    @Test
    public void CouponIntegrationTest.testRemove() {
        com.newland.beecode.domain.Coupon obj = dod.getRandomCoupon();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to initialize correctly", obj);
        java.lang.Long id = obj.getCouponId();
        org.junit.Assert.assertNotNull("Data on demand for 'Coupon' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Coupon.findCoupon(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Coupon' with identifier '" + id + "'", com.newland.beecode.domain.Coupon.findCoupon(id));
    }
    
}
