// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.CoupontCtrlDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect CoupontCtrlIntegrationTest_Roo_IntegrationTest {
    
    declare @type: CoupontCtrlIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: CoupontCtrlIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: CoupontCtrlIntegrationTest: @Transactional;
    
    @Autowired
    private CoupontCtrlDataOnDemand CoupontCtrlIntegrationTest.dod;
    
    @Test
    public void CoupontCtrlIntegrationTest.testCountCoupontCtrls() {
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", dod.getRandomCoupontCtrl());
        long count = com.newland.beecode.domain.CoupontCtrl.countCoupontCtrls();
        org.junit.Assert.assertTrue("Counter for 'CoupontCtrl' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testFindCoupontCtrl() {
        com.newland.beecode.domain.CoupontCtrl obj = dod.getRandomCoupontCtrl();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.CoupontCtrl.findCoupontCtrl(id);
        org.junit.Assert.assertNotNull("Find method for 'CoupontCtrl' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'CoupontCtrl' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testFindAllCoupontCtrls() {
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", dod.getRandomCoupontCtrl());
        long count = com.newland.beecode.domain.CoupontCtrl.countCoupontCtrls();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'CoupontCtrl', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.CoupontCtrl> result = com.newland.beecode.domain.CoupontCtrl.findAllCoupontCtrls();
        org.junit.Assert.assertNotNull("Find all method for 'CoupontCtrl' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'CoupontCtrl' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testFindCoupontCtrlEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", dod.getRandomCoupontCtrl());
        long count = com.newland.beecode.domain.CoupontCtrl.countCoupontCtrls();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.CoupontCtrl> result = com.newland.beecode.domain.CoupontCtrl.findCoupontCtrlEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'CoupontCtrl' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'CoupontCtrl' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testFlush() {
        com.newland.beecode.domain.CoupontCtrl obj = dod.getRandomCoupontCtrl();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.CoupontCtrl.findCoupontCtrl(id);
        org.junit.Assert.assertNotNull("Find method for 'CoupontCtrl' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyCoupontCtrl(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'CoupontCtrl' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testMerge() {
        com.newland.beecode.domain.CoupontCtrl obj = dod.getRandomCoupontCtrl();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.CoupontCtrl.findCoupontCtrl(id);
        boolean modified =  dod.modifyCoupontCtrl(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.CoupontCtrl merged = (com.newland.beecode.domain.CoupontCtrl) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'CoupontCtrl' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", dod.getRandomCoupontCtrl());
        com.newland.beecode.domain.CoupontCtrl obj = dod.getNewTransientCoupontCtrl(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'CoupontCtrl' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'CoupontCtrl' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void CoupontCtrlIntegrationTest.testRemove() {
        com.newland.beecode.domain.CoupontCtrl obj = dod.getRandomCoupontCtrl();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'CoupontCtrl' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.CoupontCtrl.findCoupontCtrl(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'CoupontCtrl' with identifier '" + id + "'", com.newland.beecode.domain.CoupontCtrl.findCoupontCtrl(id));
    }
    
}
