// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.Coupon;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect CouponDataOnDemand_Roo_DataOnDemand {
    
    declare @type: CouponDataOnDemand: @Component;
    
    private Random CouponDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<Coupon> CouponDataOnDemand.data;
    
    public Coupon CouponDataOnDemand.getNewTransientCoupon(int index) {
        com.newland.beecode.domain.Coupon obj = new com.newland.beecode.domain.Coupon();
        java.lang.String acctNo = "acctNo_" + index;
        if (acctNo.length() > 24) {
            acctNo  = acctNo.substring(0, 24);
        }
        obj.setAcctNo(acctNo);
        java.lang.String acctMobile = "acctMobile_" + index;
        if (acctMobile.length() > 16) {
            acctMobile  = acctMobile.substring(0, 16);
        }
        obj.setAcctMobile(acctMobile);
        java.lang.String checkCode = "checkCode_" + index;
        if (checkCode.length() > 16) {
            checkCode  = checkCode.substring(0, 16);
        }
        obj.setCheckCode(checkCode);
        java.lang.String serialNo = "serialNo_" + index;
        if (serialNo.length() > 36) {
            serialNo  = serialNo.substring(0, 36);
        }
        obj.setSerialNo(serialNo);
        obj.setCouponStatus(new Integer(index));
        obj.setMmsStatus(new Integer(index));
        java.lang.String mmsDesc = "mmsDesc_" + index;
        if (mmsDesc.length() > 100) {
            mmsDesc  = mmsDesc.substring(0, 100);
        }
        obj.setMmsDesc(mmsDesc);
        java.lang.String smsDesc = "smsDesc_" + index;
        if (smsDesc.length() > 100) {
            smsDesc  = smsDesc.substring(0, 100);
        }
        obj.setSmsDesc(smsDesc);
        obj.setSmsStatus(new Integer(index));
        obj.setRebateRate(new Integer(index).floatValue());
        obj.setTimes(new Integer(index));
        java.lang.String acctName = "acctName_" + index;
        if (acctName.length() > 10) {
            acctName  = acctName.substring(0, 10);
        }
        obj.setAcctName(acctName);
        java.lang.String mmsId = "mmsId_" + index;
        if (mmsId.length() > 20) {
            mmsId  = mmsId.substring(0, 20);
        }
        obj.setMmsId(mmsId);
        obj.setGenTime(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        java.lang.String businessType = "_" + index;
        if (businessType.length() > 2) {
            businessType  = businessType.substring(0, 2);
        }
        obj.setBusinessType(businessType);
        obj.setRemainTimes(new Integer(index));
        obj.setMarketingAct(null);
        return obj;
    }
    
    public Coupon CouponDataOnDemand.getSpecificCoupon(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        Coupon obj = data.get(index);
        return Coupon.findCoupon(obj.getCouponId());
    }
    
    public Coupon CouponDataOnDemand.getRandomCoupon() {
        init();
        Coupon obj = data.get(rnd.nextInt(data.size()));
        return Coupon.findCoupon(obj.getCouponId());
    }
    
    public boolean CouponDataOnDemand.modifyCoupon(Coupon obj) {
        return false;
    }
    
    public void CouponDataOnDemand.init() {
        data = com.newland.beecode.domain.Coupon.findCouponEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'Coupon' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.newland.beecode.domain.Coupon>();
        for (int i = 0; i < 10; i++) {
            com.newland.beecode.domain.Coupon obj = getNewTransientCoupon(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
