// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.DictViewDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect DictViewIntegrationTest_Roo_IntegrationTest {
    
    declare @type: DictViewIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: DictViewIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: DictViewIntegrationTest: @Transactional;
    
    @Autowired
    private DictViewDataOnDemand DictViewIntegrationTest.dod;
    
    @Test
    public void DictViewIntegrationTest.testCountDictViews() {
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", dod.getRandomDictView());
        long count = com.newland.beecode.domain.DictView.countDictViews();
        org.junit.Assert.assertTrue("Counter for 'DictView' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void DictViewIntegrationTest.testFindDictView() {
        com.newland.beecode.domain.DictView obj = dod.getRandomDictView();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.DictView.findDictView(id);
        org.junit.Assert.assertNotNull("Find method for 'DictView' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'DictView' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void DictViewIntegrationTest.testFindAllDictViews() {
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", dod.getRandomDictView());
        long count = com.newland.beecode.domain.DictView.countDictViews();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'DictView', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.DictView> result = com.newland.beecode.domain.DictView.findAllDictViews();
        org.junit.Assert.assertNotNull("Find all method for 'DictView' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'DictView' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void DictViewIntegrationTest.testFindDictViewEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", dod.getRandomDictView());
        long count = com.newland.beecode.domain.DictView.countDictViews();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.DictView> result = com.newland.beecode.domain.DictView.findDictViewEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'DictView' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'DictView' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void DictViewIntegrationTest.testFlush() {
        com.newland.beecode.domain.DictView obj = dod.getRandomDictView();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.DictView.findDictView(id);
        org.junit.Assert.assertNotNull("Find method for 'DictView' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyDictView(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'DictView' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DictViewIntegrationTest.testMerge() {
        com.newland.beecode.domain.DictView obj = dod.getRandomDictView();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.DictView.findDictView(id);
        boolean modified =  dod.modifyDictView(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.DictView merged = (com.newland.beecode.domain.DictView) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'DictView' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void DictViewIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", dod.getRandomDictView());
        com.newland.beecode.domain.DictView obj = dod.getNewTransientDictView(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'DictView' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'DictView' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void DictViewIntegrationTest.testRemove() {
        com.newland.beecode.domain.DictView obj = dod.getRandomDictView();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'DictView' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.DictView.findDictView(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'DictView' with identifier '" + id + "'", com.newland.beecode.domain.DictView.findDictView(id));
    }
    
}
