// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.MarketingCatalogDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MarketingCatalogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MarketingCatalogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MarketingCatalogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MarketingCatalogIntegrationTest: @Transactional;
    
    @Autowired
    private MarketingCatalogDataOnDemand MarketingCatalogIntegrationTest.dod;
    
    @Test
    public void MarketingCatalogIntegrationTest.testCountMarketingCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", dod.getRandomMarketingCatalog());
        long count = com.newland.beecode.domain.MarketingCatalog.countMarketingCatalogs();
        org.junit.Assert.assertTrue("Counter for 'MarketingCatalog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testFindMarketingCatalog() {
        com.newland.beecode.domain.MarketingCatalog obj = dod.getRandomMarketingCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingCatalog.findMarketingCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'MarketingCatalog' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MarketingCatalog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testFindAllMarketingCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", dod.getRandomMarketingCatalog());
        long count = com.newland.beecode.domain.MarketingCatalog.countMarketingCatalogs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MarketingCatalog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.MarketingCatalog> result = com.newland.beecode.domain.MarketingCatalog.findAllMarketingCatalogs();
        org.junit.Assert.assertNotNull("Find all method for 'MarketingCatalog' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MarketingCatalog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testFindMarketingCatalogEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", dod.getRandomMarketingCatalog());
        long count = com.newland.beecode.domain.MarketingCatalog.countMarketingCatalogs();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.MarketingCatalog> result = com.newland.beecode.domain.MarketingCatalog.findMarketingCatalogEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MarketingCatalog' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MarketingCatalog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testFlush() {
        com.newland.beecode.domain.MarketingCatalog obj = dod.getRandomMarketingCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingCatalog.findMarketingCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'MarketingCatalog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMarketingCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MarketingCatalog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testMerge() {
        com.newland.beecode.domain.MarketingCatalog obj = dod.getRandomMarketingCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingCatalog.findMarketingCatalog(id);
        boolean modified =  dod.modifyMarketingCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.MarketingCatalog merged = (com.newland.beecode.domain.MarketingCatalog) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'MarketingCatalog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", dod.getRandomMarketingCatalog());
        com.newland.beecode.domain.MarketingCatalog obj = dod.getNewTransientMarketingCatalog(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MarketingCatalog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MarketingCatalog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void MarketingCatalogIntegrationTest.testRemove() {
        com.newland.beecode.domain.MarketingCatalog obj = dod.getRandomMarketingCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingCatalog.findMarketingCatalog(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MarketingCatalog' with identifier '" + id + "'", com.newland.beecode.domain.MarketingCatalog.findMarketingCatalog(id));
    }
    
}
