// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.MarketingActDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect MarketingActIntegrationTest_Roo_IntegrationTest {
    
    declare @type: MarketingActIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: MarketingActIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: MarketingActIntegrationTest: @Transactional;
    
    @Autowired
    private MarketingActDataOnDemand MarketingActIntegrationTest.dod;
    
    @Test
    public void MarketingActIntegrationTest.testCountMarketingActs() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", dod.getRandomMarketingAct());
        long count = com.newland.beecode.domain.MarketingAct.countMarketingActs();
        org.junit.Assert.assertTrue("Counter for 'MarketingAct' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void MarketingActIntegrationTest.testFindMarketingAct() {
        com.newland.beecode.domain.MarketingAct obj = dod.getRandomMarketingAct();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", obj);
        java.lang.Long id = obj.getActNo();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingAct.findMarketingAct(id);
        org.junit.Assert.assertNotNull("Find method for 'MarketingAct' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'MarketingAct' returned the incorrect identifier", id, obj.getActNo());
    }
    
    @Test
    public void MarketingActIntegrationTest.testFindAllMarketingActs() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", dod.getRandomMarketingAct());
        long count = com.newland.beecode.domain.MarketingAct.countMarketingActs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'MarketingAct', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.MarketingAct> result = com.newland.beecode.domain.MarketingAct.findAllMarketingActs();
        org.junit.Assert.assertNotNull("Find all method for 'MarketingAct' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'MarketingAct' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void MarketingActIntegrationTest.testFindMarketingActEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", dod.getRandomMarketingAct());
        long count = com.newland.beecode.domain.MarketingAct.countMarketingActs();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.MarketingAct> result = com.newland.beecode.domain.MarketingAct.findMarketingActEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'MarketingAct' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'MarketingAct' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void MarketingActIntegrationTest.testFlush() {
        com.newland.beecode.domain.MarketingAct obj = dod.getRandomMarketingAct();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", obj);
        java.lang.Long id = obj.getActNo();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingAct.findMarketingAct(id);
        org.junit.Assert.assertNotNull("Find method for 'MarketingAct' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyMarketingAct(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'MarketingAct' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingActIntegrationTest.testMerge() {
        com.newland.beecode.domain.MarketingAct obj = dod.getRandomMarketingAct();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", obj);
        java.lang.Long id = obj.getActNo();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingAct.findMarketingAct(id);
        boolean modified =  dod.modifyMarketingAct(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.MarketingAct merged = (com.newland.beecode.domain.MarketingAct) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getActNo(), id);
        org.junit.Assert.assertTrue("Version for 'MarketingAct' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void MarketingActIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", dod.getRandomMarketingAct());
        com.newland.beecode.domain.MarketingAct obj = dod.getNewTransientMarketingAct(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'MarketingAct' identifier to be null", obj.getActNo());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'MarketingAct' identifier to no longer be null", obj.getActNo());
    }
    
    @Test
    public void MarketingActIntegrationTest.testRemove() {
        com.newland.beecode.domain.MarketingAct obj = dod.getRandomMarketingAct();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to initialize correctly", obj);
        java.lang.Long id = obj.getActNo();
        org.junit.Assert.assertNotNull("Data on demand for 'MarketingAct' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.MarketingAct.findMarketingAct(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'MarketingAct' with identifier '" + id + "'", com.newland.beecode.domain.MarketingAct.findMarketingAct(id));
    }
    
}
