// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.OrganizationDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect OrganizationIntegrationTest_Roo_IntegrationTest {
    
    declare @type: OrganizationIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: OrganizationIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: OrganizationIntegrationTest: @Transactional;
    
    @Autowired
    private OrganizationDataOnDemand OrganizationIntegrationTest.dod;
    
    @Test
    public void OrganizationIntegrationTest.testCountOrganizations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", dod.getRandomOrganization());
        long count = com.newland.beecode.domain.Organization.countOrganizations();
        org.junit.Assert.assertTrue("Counter for 'Organization' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void OrganizationIntegrationTest.testFindOrganization() {
        com.newland.beecode.domain.Organization obj = dod.getRandomOrganization();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Organization.findOrganization(id);
        org.junit.Assert.assertNotNull("Find method for 'Organization' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Organization' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void OrganizationIntegrationTest.testFindAllOrganizations() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", dod.getRandomOrganization());
        long count = com.newland.beecode.domain.Organization.countOrganizations();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Organization', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.Organization> result = com.newland.beecode.domain.Organization.findAllOrganizations();
        org.junit.Assert.assertNotNull("Find all method for 'Organization' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Organization' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void OrganizationIntegrationTest.testFindOrganizationEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", dod.getRandomOrganization());
        long count = com.newland.beecode.domain.Organization.countOrganizations();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.Organization> result = com.newland.beecode.domain.Organization.findOrganizationEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Organization' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Organization' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void OrganizationIntegrationTest.testFlush() {
        com.newland.beecode.domain.Organization obj = dod.getRandomOrganization();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Organization.findOrganization(id);
        org.junit.Assert.assertNotNull("Find method for 'Organization' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyOrganization(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Organization' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganizationIntegrationTest.testMerge() {
        com.newland.beecode.domain.Organization obj = dod.getRandomOrganization();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Organization.findOrganization(id);
        boolean modified =  dod.modifyOrganization(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.Organization merged = (com.newland.beecode.domain.Organization) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Organization' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void OrganizationIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", dod.getRandomOrganization());
        com.newland.beecode.domain.Organization obj = dod.getNewTransientOrganization(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Organization' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Organization' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void OrganizationIntegrationTest.testRemove() {
        com.newland.beecode.domain.Organization obj = dod.getRandomOrganization();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Organization' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Organization.findOrganization(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Organization' with identifier '" + id + "'", com.newland.beecode.domain.Organization.findOrganization(id));
    }
    
}
