// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.PartnerCatalogDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartnerCatalogIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PartnerCatalogIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PartnerCatalogIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PartnerCatalogIntegrationTest: @Transactional;
    
    @Autowired
    private PartnerCatalogDataOnDemand PartnerCatalogIntegrationTest.dod;
    
    @Test
    public void PartnerCatalogIntegrationTest.testCountPartnerCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", dod.getRandomPartnerCatalog());
        long count = com.newland.beecode.domain.PartnerCatalog.countPartnerCatalogs();
        org.junit.Assert.assertTrue("Counter for 'PartnerCatalog' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testFindPartnerCatalog() {
        com.newland.beecode.domain.PartnerCatalog obj = dod.getRandomPartnerCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'PartnerCatalog' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'PartnerCatalog' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testFindAllPartnerCatalogs() {
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", dod.getRandomPartnerCatalog());
        long count = com.newland.beecode.domain.PartnerCatalog.countPartnerCatalogs();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'PartnerCatalog', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.PartnerCatalog> result = com.newland.beecode.domain.PartnerCatalog.findAllPartnerCatalogs();
        org.junit.Assert.assertNotNull("Find all method for 'PartnerCatalog' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'PartnerCatalog' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testFindPartnerCatalogEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", dod.getRandomPartnerCatalog());
        long count = com.newland.beecode.domain.PartnerCatalog.countPartnerCatalogs();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.PartnerCatalog> result = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalogEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'PartnerCatalog' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'PartnerCatalog' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testFlush() {
        com.newland.beecode.domain.PartnerCatalog obj = dod.getRandomPartnerCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalog(id);
        org.junit.Assert.assertNotNull("Find method for 'PartnerCatalog' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPartnerCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'PartnerCatalog' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testMerge() {
        com.newland.beecode.domain.PartnerCatalog obj = dod.getRandomPartnerCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalog(id);
        boolean modified =  dod.modifyPartnerCatalog(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.PartnerCatalog merged = (com.newland.beecode.domain.PartnerCatalog) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'PartnerCatalog' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", dod.getRandomPartnerCatalog());
        com.newland.beecode.domain.PartnerCatalog obj = dod.getNewTransientPartnerCatalog(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'PartnerCatalog' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'PartnerCatalog' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PartnerCatalogIntegrationTest.testRemove() {
        com.newland.beecode.domain.PartnerCatalog obj = dod.getRandomPartnerCatalog();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'PartnerCatalog' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalog(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'PartnerCatalog' with identifier '" + id + "'", com.newland.beecode.domain.PartnerCatalog.findPartnerCatalog(id));
    }
    
}
