// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.PartnerCatalog;
import java.util.List;
import java.util.Random;
import org.springframework.stereotype.Component;

privileged aspect PartnerCatalogDataOnDemand_Roo_DataOnDemand {
    
    declare @type: PartnerCatalogDataOnDemand: @Component;
    
    private Random PartnerCatalogDataOnDemand.rnd = new java.security.SecureRandom();
    
    private List<PartnerCatalog> PartnerCatalogDataOnDemand.data;
    
    public PartnerCatalog PartnerCatalogDataOnDemand.getNewTransientPartnerCatalog(int index) {
        com.newland.beecode.domain.PartnerCatalog obj = new com.newland.beecode.domain.PartnerCatalog();
        java.lang.String catalogName = "catalogName_" + index;
        if (catalogName.length() > 32) {
            catalogName  = catalogName.substring(0, 32);
        }
        obj.setCatalogName(catalogName);
        obj.setCreateTime(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        obj.setUpdateTime(new java.util.GregorianCalendar(java.util.Calendar.getInstance().get(java.util.Calendar.YEAR), java.util.Calendar.getInstance().get(java.util.Calendar.MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.DAY_OF_MONTH), java.util.Calendar.getInstance().get(java.util.Calendar.HOUR_OF_DAY), java.util.Calendar.getInstance().get(java.util.Calendar.MINUTE), java.util.Calendar.getInstance().get(java.util.Calendar.SECOND) + new Double(Math.random() * 1000).intValue()).getTime());
        return obj;
    }
    
    public PartnerCatalog PartnerCatalogDataOnDemand.getSpecificPartnerCatalog(int index) {
        init();
        if (index < 0) index = 0;
        if (index > (data.size() - 1)) index = data.size() - 1;
        PartnerCatalog obj = data.get(index);
        return PartnerCatalog.findPartnerCatalog(obj.getId());
    }
    
    public PartnerCatalog PartnerCatalogDataOnDemand.getRandomPartnerCatalog() {
        init();
        PartnerCatalog obj = data.get(rnd.nextInt(data.size()));
        return PartnerCatalog.findPartnerCatalog(obj.getId());
    }
    
    public boolean PartnerCatalogDataOnDemand.modifyPartnerCatalog(PartnerCatalog obj) {
        return false;
    }
    
    public void PartnerCatalogDataOnDemand.init() {
        data = com.newland.beecode.domain.PartnerCatalog.findPartnerCatalogEntries(0, 10);
        if (data == null) throw new IllegalStateException("Find entries implementation for 'PartnerCatalog' illegally returned null");
        if (!data.isEmpty()) {
            return;
        }
        
        data = new java.util.ArrayList<com.newland.beecode.domain.PartnerCatalog>();
        for (int i = 0; i < 10; i++) {
            com.newland.beecode.domain.PartnerCatalog obj = getNewTransientPartnerCatalog(i);
            obj.persist();
            obj.flush();
            data.add(obj);
        }
    }
    
}
