// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.PartnerDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect PartnerIntegrationTest_Roo_IntegrationTest {
    
    declare @type: PartnerIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: PartnerIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: PartnerIntegrationTest: @Transactional;
    
    @Autowired
    private PartnerDataOnDemand PartnerIntegrationTest.dod;
    
    @Test
    public void PartnerIntegrationTest.testCountPartners() {
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = com.newland.beecode.domain.Partner.countPartners();
        org.junit.Assert.assertTrue("Counter for 'Partner' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void PartnerIntegrationTest.testFindPartner() {
        com.newland.beecode.domain.Partner obj = dod.getRandomPartner();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Partner.findPartner(id);
        org.junit.Assert.assertNotNull("Find method for 'Partner' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Partner' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void PartnerIntegrationTest.testFindAllPartners() {
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = com.newland.beecode.domain.Partner.countPartners();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Partner', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.Partner> result = com.newland.beecode.domain.Partner.findAllPartners();
        org.junit.Assert.assertNotNull("Find all method for 'Partner' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Partner' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void PartnerIntegrationTest.testFindPartnerEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        long count = com.newland.beecode.domain.Partner.countPartners();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.Partner> result = com.newland.beecode.domain.Partner.findPartnerEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Partner' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Partner' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void PartnerIntegrationTest.testFlush() {
        com.newland.beecode.domain.Partner obj = dod.getRandomPartner();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Partner.findPartner(id);
        org.junit.Assert.assertNotNull("Find method for 'Partner' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyPartner(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Partner' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerIntegrationTest.testMerge() {
        com.newland.beecode.domain.Partner obj = dod.getRandomPartner();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Partner.findPartner(id);
        boolean modified =  dod.modifyPartner(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.Partner merged = (com.newland.beecode.domain.Partner) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Partner' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void PartnerIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", dod.getRandomPartner());
        com.newland.beecode.domain.Partner obj = dod.getNewTransientPartner(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Partner' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Partner' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void PartnerIntegrationTest.testRemove() {
        com.newland.beecode.domain.Partner obj = dod.getRandomPartner();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Partner' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Partner.findPartner(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Partner' with identifier '" + id + "'", com.newland.beecode.domain.Partner.findPartner(id));
    }
    
}
