// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.newland.beecode.domain;

import com.newland.beecode.domain.RolesDataOnDemand;
import org.junit.Test;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.test.context.ContextConfiguration;
import org.springframework.test.context.junit4.SpringJUnit4ClassRunner;
import org.springframework.transaction.annotation.Transactional;

privileged aspect RolesIntegrationTest_Roo_IntegrationTest {
    
    declare @type: RolesIntegrationTest: @RunWith(SpringJUnit4ClassRunner.class);
    
    declare @type: RolesIntegrationTest: @ContextConfiguration(locations = "classpath:/META-INF/spring/applicationContext.xml");
    
    declare @type: RolesIntegrationTest: @Transactional;
    
    @Autowired
    private RolesDataOnDemand RolesIntegrationTest.dod;
    
    @Test
    public void RolesIntegrationTest.testCountRoleses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = com.newland.beecode.domain.Roles.countRoleses();
        org.junit.Assert.assertTrue("Counter for 'Roles' incorrectly reported there were no entries", count > 0);
    }
    
    @Test
    public void RolesIntegrationTest.testFindRoles() {
        com.newland.beecode.domain.Roles obj = dod.getRandomRoles();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Roles.findRoles(id);
        org.junit.Assert.assertNotNull("Find method for 'Roles' illegally returned null for id '" + id + "'", obj);
        org.junit.Assert.assertEquals("Find method for 'Roles' returned the incorrect identifier", id, obj.getId());
    }
    
    @Test
    public void RolesIntegrationTest.testFindAllRoleses() {
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = com.newland.beecode.domain.Roles.countRoleses();
        org.junit.Assert.assertTrue("Too expensive to perform a find all test for 'Roles', as there are " + count + " entries; set the findAllMaximum to exceed this value or set findAll=false on the integration test annotation to disable the test", count < 250);
        java.util.List<com.newland.beecode.domain.Roles> result = com.newland.beecode.domain.Roles.findAllRoleses();
        org.junit.Assert.assertNotNull("Find all method for 'Roles' illegally returned null", result);
        org.junit.Assert.assertTrue("Find all method for 'Roles' failed to return any data", result.size() > 0);
    }
    
    @Test
    public void RolesIntegrationTest.testFindRolesEntries() {
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        long count = com.newland.beecode.domain.Roles.countRoleses();
        if (count > 20) count = 20;
        java.util.List<com.newland.beecode.domain.Roles> result = com.newland.beecode.domain.Roles.findRolesEntries(0, (int) count);
        org.junit.Assert.assertNotNull("Find entries method for 'Roles' illegally returned null", result);
        org.junit.Assert.assertEquals("Find entries method for 'Roles' returned an incorrect number of entries", count, result.size());
    }
    
    @Test
    public void RolesIntegrationTest.testFlush() {
        com.newland.beecode.domain.Roles obj = dod.getRandomRoles();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Roles.findRoles(id);
        org.junit.Assert.assertNotNull("Find method for 'Roles' illegally returned null for id '" + id + "'", obj);
        boolean modified =  dod.modifyRoles(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        obj.flush();
        org.junit.Assert.assertTrue("Version for 'Roles' failed to increment on flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolesIntegrationTest.testMerge() {
        com.newland.beecode.domain.Roles obj = dod.getRandomRoles();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Roles.findRoles(id);
        boolean modified =  dod.modifyRoles(obj);
        java.lang.Integer currentVersion = obj.getVersion();
        com.newland.beecode.domain.Roles merged = (com.newland.beecode.domain.Roles) obj.merge();
        obj.flush();
        org.junit.Assert.assertEquals("Identifier of merged object not the same as identifier of original object", merged.getId(), id);
        org.junit.Assert.assertTrue("Version for 'Roles' failed to increment on merge and flush directive", (currentVersion != null && obj.getVersion() > currentVersion) || !modified);
    }
    
    @Test
    public void RolesIntegrationTest.testPersist() {
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", dod.getRandomRoles());
        com.newland.beecode.domain.Roles obj = dod.getNewTransientRoles(Integer.MAX_VALUE);
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to provide a new transient entity", obj);
        org.junit.Assert.assertNull("Expected 'Roles' identifier to be null", obj.getId());
        obj.persist();
        obj.flush();
        org.junit.Assert.assertNotNull("Expected 'Roles' identifier to no longer be null", obj.getId());
    }
    
    @Test
    public void RolesIntegrationTest.testRemove() {
        com.newland.beecode.domain.Roles obj = dod.getRandomRoles();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to initialize correctly", obj);
        java.lang.Long id = obj.getId();
        org.junit.Assert.assertNotNull("Data on demand for 'Roles' failed to provide an identifier", id);
        obj = com.newland.beecode.domain.Roles.findRoles(id);
        obj.remove();
        obj.flush();
        org.junit.Assert.assertNull("Failed to remove 'Roles' with identifier '" + id + "'", com.newland.beecode.domain.Roles.findRoles(id));
    }
    
}
