package org.tempuri;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.logging.Logger;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * <p>
 * An example of how this class may be used:
 * 
 * <pre>
 * MMS service = new MMS();
 * MMSSoap portType = service.getMMSSoap();
 * portType.sendMMS(...);
 * </pre>
 * 
 * </p>
 * 
 */
@WebServiceClient(name = "MMS", targetNamespace = "http://tempuri.org/", wsdlLocation = "http://mmsplat.eucp.b2m.cn/mmscenterinterface/MMS.asmx?wsdl")
public class MMS extends Service {

	private final static URL MMS_WSDL_LOCATION;
	private final static Logger logger = Logger.getLogger(org.tempuri.MMS.class
			.getName());

	static {
		URL url = null;
		try {
			URL baseUrl;
			baseUrl = org.tempuri.MMS.class.getResource(".");
			url = new URL(baseUrl, "http://mmsplat.eucp.b2m.cn/mmscenterinterface/MMS.asmx?wsdl");
		} catch (MalformedURLException e) {
			logger
					.warning("Failed to create URL for the wsdl Location: 'http://mmsplat.eucp.b2m.cn/mmscenterinterface/MMS.asmx?wsdl', retrying as a local file");
			logger.warning(e.getMessage());
		}
		MMS_WSDL_LOCATION = url;
	}

	public MMS(URL wsdlLocation, QName serviceName) {
		super(wsdlLocation, serviceName);
	}

	public MMS() {
		super(MMS_WSDL_LOCATION, new QName("http://tempuri.org/", "MMS"));
	}

	/**
	 * 
	 * @return returns MMSSoap
	 */
	@WebEndpoint(name = "MMSSoap")
	public MMSSoap getMMSSoap() {
		return super.getPort(new QName("http://tempuri.org/", "MMSSoap"),
				MMSSoap.class);
	}

	/**
	 * 
	 * @return returns MMSSoap
	 */
	@WebEndpoint(name = "MMSSoap12")
	public MMSSoap getMMSSoap12() {
		return super.getPort(new QName("http://tempuri.org/", "MMSSoap12"),
				MMSSoap.class);
	}

}
