package org.tempuri;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI. JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 * 
 */
@WebService(name = "MMSSoap", targetNamespace = "http://tempuri.org/")
public interface MMSSoap {

	/**
	 * ���Ͳ���
	 * 
	 * @param password
	 * @param userName
	 * @param title
	 * @param mmsContent
	 * @param userNumbers
	 * @param sendType
	 * @return returns java.lang.String
	 */
	@WebMethod(operationName = "SendMMS", action = "http://tempuri.org/SendMMS")
	@WebResult(name = "SendMMSResult", targetNamespace = "http://tempuri.org/")
	@RequestWrapper(localName = "SendMMS", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendMMS")
	@ResponseWrapper(localName = "SendMMSResponse", targetNamespace = "http://tempuri.org/", className = "org.tempuri.SendMMSResponse")
	public String sendMMS(
			@WebParam(name = "userName", targetNamespace = "http://tempuri.org/") String userName,
			@WebParam(name = "password", targetNamespace = "http://tempuri.org/") String password,
			@WebParam(name = "title", targetNamespace = "http://tempuri.org/") String title,
			@WebParam(name = "userNumbers", targetNamespace = "http://tempuri.org/") String userNumbers,
			@WebParam(name = "MMSContent", targetNamespace = "http://tempuri.org/") byte[] mmsContent,
			@WebParam(name = "sendType", targetNamespace = "http://tempuri.org/") int sendType);

}
